frends=[]
frends.append('Azizjon')
frends.append('Nizomiddin')
frends.append('Abbosxon')
frends.append('Maxmud')
frends.append('Isroil')
frends.append('ismattila')
print('Mexmonga chaqirilganlar ro\'yxati>>>',frends)
frends.remove('Maxmud')
frends.remove('Isroil')
frends.remove('ismattila')
print('Mexmonga keladiganlar ro\'yxati>>>',frends)
frends.append('Farxod')
print('Ro\'yxat oxiriga Farxod qo\'shildi',frends)
frends.insert(0,'Aziz')
print('Ro\'yxat boshiga Aziz qo\'shildi',frends)
frends.insert(3,'Ravshan')
print('Ro\'yxat o\'rtasiga Ravshan qo\'shildi',frends)
mexmonlar=[]
mexmonlar.append(frends.pop(0))
mexmonlar.append(frends.pop(1))
mexmonlar.append(frends.pop(2))
print('\n Kelgan mehmonlar',mexmonlar)

